global:
  scrape_interval: 5s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['172.17.0.1:9100']
            
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.72:9090']
          
